quarkus:
  http:
    cors: true
  mongodb:
    database: screenCastDB
    connection-string: mongodb://mongodb-24-centos7-sca-project.apps-crc.testing:27017
  jaeger:
    service-name: scapersistservice
    sampler-type: const
    sampler-param: 1
    endpoint: http://jaeger-all-in-one-inmemory-collector-sca-project.apps-crc.testing:14286/api/traces



"%local":
  quarkus:
    profile: local
    mongodb:
      connection-string: mongodb://mongodb-24-centos7-sca-project.apps-crc.testing:27017



"%openshift":
  quarkus:
    profile: openshift
    mongodb:
      connection-string: mongodb://mongodb-24-centos7-sca-project.apps-crc.testing:27017
    jaeger:
      endpoint: http://jaeger-all-in-one-inmemory-collector-sca-project.apps-crc.testing:14286/api/traces